name: Build, test and make packages

on:
  workflow_call:
    inputs:
      python-version:
        description: 'A version of a python interpreter to use'
        default: '3.7'
        required: false
        type: string
      os:
        description: 'A container which is used to make a build'
        default: ubuntu-20.04
        required: false
        type: string
      make-packages:
        description: 'Is making packages required?'
        default: false
        required: false
        type: boolean

jobs:
  run:

    runs-on: ${{ inputs.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            override: true

      - name: Build and test
        working-directory: ./lib
        run: |
          cargo check
          cargo build
          RUST_LOG=hyperon=debug cargo test

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Conan
        uses: turtlebrowser/get-conan@v1.1
        with:
          version: 1.57.0

      - name: Install cbindgen
        uses: actions-rs/cargo@v1.0.1
        with:
          command: install
          args: cbindgen

      - name: Setup C API build
        run: |
          mkdir -p build
          cd build
          # specify C compiler as conan could not find it automatically
          # see https://github.com/conan-io/conan/issues/4322
          cmake -DPython3_EXECUTABLE=`which python` -DCMAKE_C_COMPILER=gcc ..

      - name: Build C API
        working-directory: ./build
        run: make

      - name: Test C API
        working-directory: ./build
        run: make check

      - name: Build package
        if: inputs.make-packages
        working-directory: ./python
        run: |
          python -m build
          tar zcf dist-${{ inputs.os }}-py${{ inputs.python-version }}.tar.gz dist

      - name: Upload artifacts
        if: inputs.make-packages
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ inputs.os }}-py${{ inputs.python-version }}.tar.gz
          path: ./python/dist-${{ inputs.os }}-py${{ inputs.python-version }}.tar.gz
