name: Test workflow

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-14 ]
        try: [ 0 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: ${{ inputs.cmake-version }}

      - name: Install Conan
        uses: turtlebrowser/get-conan@v1.2
        with:
          version: "1.64"

      - name: Setup Conan profile
        run: |
          conan profile new --detect default

      - name: Run conan install
        working-directory: ./c
        run: |
          cmake -E env CC= CXX= conan install --build -- .

          
